accept = ["200", "429"]

# Decrease concurrent requests to avoid flooding target servers when running
# in highly parallel CI jobs
max_concurrency = 10
max_retries = 5
no_progress = true
retry_wait_time = 4
